version: '3.3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: pollio
      MYSQL_USER: rohit
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    expose:
      - 3306

    volumes:
      - my-app:/var/lib/mysql

  web:
    build: .
    ports:
      - 4000:4000
    expose:
      - 4000

volumes:
  my-app: